//
//  PlanetInfo.swift
//  SolarisProject
//
//  Created by Felipe Dias on 23/12/20.
//

import SwiftUI

let comparisonTitle = ["Planet type", "Distance from the Sun", "Rotation Period", "Translational Period", "Planet Radius", "Circumference", "Gravity", "Escape Velocity", "Temperature", "Number of moons"]

struct PlanetInfo: Identifiable {
    var id = UUID()
    var name: String
    var type: String
    var sunD: String
    var transl: String
    var rotat: String
    var radius: String
    var circum: String
    var mass: String
    var gravity: String
    var escapeV: String
    var temperature: String
    var moons: String
}

//Metric Unit Array//
let planetInfo = [
    PlanetInfo(name: "Mercury",
               type: "Terrestrial",
               sunD: "57,909,227\nkm",
               transl: "87.96 Earth\ndays",
               rotat: "58.7 Earth\ndays",
               radius: "2,440 km",
               circum: "15,329 km",
               mass: "3.29 × 10^23 kg",
               gravity: "3.7 m/s2",
               escapeV: "15,300 km/h",
               temperature: "430°C",
               moons: "0"),
    PlanetInfo(name: "Venus",
               type: "Terrestrial",
               sunD: "108,209,475\nkm",
               transl: "224.68 Earth\ndays",
               rotat: "243 Earth\ndays",
               radius: "6,052 km",
               circum: "38,024 km",
               mass: "4.87 × 10^24 kg",
               gravity: "8.87 m/s2",
               escapeV: "37,296 km/h",
               temperature: "471°C",
               moons: "0"),
    PlanetInfo(name: "Earth",
               type: "Terrestrial",
               sunD: "149,598,262\nkm",
               transl: "365.26 Earth\ndays",
               rotat: "24 Earth hours",
               radius: "6,371 km",
               circum: "40,030 km",
               mass: "5.98 × 10^24 kg",
               gravity: "9.8 m/s2",
               escapeV: "40,284 km/h",
               temperature: "16°C",
               moons: "1"),
    PlanetInfo(name: "Mars",
               type: "Terrestrial",
               sunD: "227,943,824\nkm",
               transl: "686.98 Earth\ndays",
               rotat: "24.6 Earth\nhours",
               radius: "3,389 km",
               circum: "21,297 km",
               mass: "6.39 × 10^23 kg",
               gravity: "3.71 m/s2",
               escapeV: "18,108 km/h",
               temperature: "-28°C",
               moons: "2"),
    PlanetInfo(name: "Jupiter",
               type: "Gas Giant",
               sunD: "778,340,821\nkm",
               transl: "11.862 Earth\ndays",
               rotat: "9.84 Earth\nhours",
               radius: "69,911 km",
               circum: "439,264 km",
               mass: "1.90 × 10^27 kg",
               gravity: "24.79 m/s2",
               escapeV: "216,720 km/h",
               temperature: "-108°C",
               moons: "79"),
    PlanetInfo(name: "Saturn",
               type: "Gas Giant",
               sunD: "1,426,666,422\nkm",
               transl: "29.456 Earth\ndays",
               rotat: "10.2 Earth\nhours",
               radius: "58,232 km",
               circum: "365,882 km",
               mass: "5.68 × 10^26 kg",
               gravity: "10.4 m/s2",
               escapeV: "129,924 km/h",
               temperature: "-138°C",
               moons: "82"),
    PlanetInfo(name: "Uranus",
               type: "Ice Giant",
               sunD: "2,870,658,186\nkm",
               transl: "84.07 Earth\ndays",
               rotat: "17.9 Earth\nhours",
               radius: "25,362 km",
               circum: "159,354 km",
               mass: "8.68 × 10^25 kg",
               gravity: "8.87 m/s2",
               escapeV: "76,968 km/h",
               temperature: "-195°C",
               moons: "27"),
    PlanetInfo(name: "Neptune",
               type: "Ice Giant",
               sunD: "4,498,396,441\nkm",
               transl: "164.81 Earth\ndays",
               rotat: "19.1 Earth\nhours",
               radius: "24,622 km",
               circum: "154,705 km",
               mass: "1.02 × 10^26 kg",
               gravity: "11.15 m/s2",
               escapeV: "84,816 km/h",
               temperature: "-201°C",
               moons: "14"),
]

//Astronomical Unit Array//
let planetInfo2 = [
    PlanetInfo(name: "Mercury",
               type: "Terrestrial",
               sunD: "0.39 AU",
               transl: "87.96 Earth\ndays",
               rotat: "58.7 Earth\ndays",
               radius: "0.4 RE",
               circum: "0.38 CE",
               mass: "0.055 ME",
               gravity: "3.7 m/s2",
               escapeV: "15,300 km/h",
               temperature: "430°C",
               moons: "0"),
    PlanetInfo(name: "Venus",
               type: "Terrestrial",
               sunD: "0.723 AU",
               transl: "224.68 Earth\ndays",
               rotat: "243 Earth\ndays",
               radius: "0.9 RE",
               circum: "0.95 CE",
               mass: "0.815 ME",
               gravity: "8.87 m/s2",
               escapeV: "37,296 km/h",
               temperature: "471°C",
               moons: "0"),
    PlanetInfo(name: "Earth",
               type: "Terrestrial",
               sunD: "1 AU",
               transl: "365.26 Earth\ndays",
               rotat: "24 Earth hours",
               radius: "1 RE",
               circum: "1 CE",
               mass: "1 ME",
               gravity: "9.8 m/s2",
               escapeV: "40,284 km/h",
               temperature: "16°C",
               moons: "1"),
    PlanetInfo(name: "Mars",
               type: "Terrestrial",
               sunD: "1.524 AU",
               transl: "686.98 Earth\ndays",
               rotat: "24.6 Earth\nhours",
               radius: "0.52 RE",
               circum: "0.53 CE",
               mass: "0.107 ME",
               gravity: "3.71 m/s2",
               escapeV: "18,108 km/h",
               temperature: "-28°C",
               moons: "2"),
    PlanetInfo(name: "Jupiter",
               type: "Gas Giant",
               sunD: "5.203 AU",
               transl: "11.862 Earth\ndays",
               rotat: "9.84 Earth\nhours",
               radius: "10.1 RE",
               circum: "10.97 CE",
               mass: "317.8 ME",
               gravity: "24.79 m/s2",
               escapeV: "216,720 km/h",
               temperature: "-108°C",
               moons: "79"),
    PlanetInfo(name: "Saturn",
               type: "Gas Giant",
               sunD: "9.539 AU",
               transl: "29.456 Earth\ndays",
               rotat: "10.2 Earth\nhours",
               radius: "9 RE",
               circum: "9.14 CE",
               mass: "95.16 ME",
               gravity: "10.4 m/s2",
               escapeV: "129,924 km/h",
               temperature: "-138°C",
               moons: "82"),
    PlanetInfo(name: "Uranus",
               type: "Ice Giant",
               sunD: "19.18 AU",
               transl: "84.07 Earth\ndays",
               rotat: "17.9 Earth\nhours",
               radius: "4 RE",
               circum: "3.98 CE",
               mass: "14.53 ME",
               gravity: "8.87 m/s2",
               escapeV: "76,968 km/h",
               temperature: "-195°C",
               moons: "27"),
    PlanetInfo(name: "Neptune",
               type: "Ice Giant",
               sunD: "30.06 AU",
               transl: "164.81 Earth\ndays",
               rotat: "19.1 Earth\nhours",
               radius: "3.8 RE",
               circum: "3.86 CE",
               mass: "17.15 ME",
               gravity: "11.15 m/s2",
               escapeV: "84,816 km/h",
               temperature: "-201°C",
               moons: "14"),
]

//English Unit Array//
let planetInfo3 = [
    PlanetInfo(name: "Mercury",
               type: "Terrestrial",
               sunD: "35,983,125\nmiles",
               transl: "87.96 Earth\ndays",
               rotat: "58.7 Earth\ndays",
               radius: "1,516 miles",
               circum: "9,525\nmiles",
               mass: "7.25 × 10^23 lbs",
               gravity: "12.1 f/s2",
               escapeV: "9,507 mph",
               temperature: "800°F",
               moons: "0"),
    PlanetInfo(name: "Venus",
               type: "Terrestrial",
               sunD: "67,238,251\nmiles",
               transl: "224.68 Earth\ndays",
               rotat: "243 Earth\ndays",
               radius: "3,760 miles",
               circum: "23,627\nmiles",
               mass: "1.07 × 10^25 lbs",
               gravity: "29.1 f/s2",
               escapeV: "23,175 mph",
               temperature: "880°F",
               moons: "0"),
    PlanetInfo(name: "Earth",
               type: "Terrestrial",
               sunD: "92,956,050\nmiles",
               transl: "365.26 Earth\ndays",
               rotat: "24 Earth hours",
               radius: "3,959 miles",
               circum: "24,874\nmiles",
               mass: "1.32 × 10^25 lbs",
               gravity: "32.0 f/s2",
               escapeV: "25,031mph",
               temperature: "61°F",
               moons: "1"),
    PlanetInfo(name: "Mars",
               type: "Terrestrial",
               sunD: "141,637,725\nmiles",
               transl: "686.98 Earth\ndays",
               rotat: "24.6 Earth\nhours",
               radius: "2,106 miles",
               circum: "13,233\nmiles",
               mass: "1.40 × 10^24 lbs",
               gravity: "12.2 f/s2",
               escapeV: "11,252 mph",
               temperature: "-20°F",
               moons: "2"),
    PlanetInfo(name: "Jupiter",
               type: "Gas Giant",
               sunD: "483,638,564\nmiles",
               transl: "11.862 Earth\ndays",
               rotat: "9.84 Earth\nhours",
               radius: "43,441 miles",
               circum: "272,946\nmiles",
               mass: "4.19 × 10^27 lbs",
               gravity: "81.3 f/s2",
               escapeV: "134,664 mph",
               temperature: "-162°F",
               moons: "79"),
    PlanetInfo(name: "Saturn",
               type: "Gas Giant",
               sunD: "886,489,415\nmiles",
               transl: "29.456 Earth\ndays",
               rotat: "10.2 Earth\nhours",
               radius: "36,184 miles",
               circum: "227,349\nmiles",
               mass: "1.25 × 10^27 lbs",
               gravity: "34.3 f/s2",
               escapeV: "80,731 mph",
               temperature: "-218°F",
               moons: "82"),
    PlanetInfo(name: "Uranus",
               type: "Ice Giant",
               sunD: "1,783,744,300\nmiles",
               transl: "84.07 Earth\ndays",
               rotat: "17.9 Earth\nhours",
               radius: "15,759 miles",
               circum: "99,018\nmiles",
               mass: "1.91 × 10^26 lbs",
               gravity: "29.1 f/s2",
               escapeV: "47,826 mph",
               temperature: "-320°F",
               moons: "27"),
    PlanetInfo(name: "Neptune",
               type: "Ice Giant",
               sunD: "2,795,173,960\nmiles",
               transl: "164.81 Earth\ndays",
               rotat: "19.1 Earth\nhours",
               radius: "15,299 miles",
               circum: "96,129\nmiles",
               mass: "2.25 × 10^26 lbs",
               gravity: "36.6 f/s2",
               escapeV: "52,702 mph",
               temperature: "-331°F",
               moons: "14"),
]

struct SizeCompare: Identifiable {
    var id = UUID()
    var size: CGFloat
    var color: Color
}

let sizeCompare = [
    SizeCompare(size: CGFloat(screen.width * 0.02),
                color: Color(#colorLiteral(red: 0.501960814, green: 0.501960814, blue: 0.501960814, alpha: 1))),
    SizeCompare(size: CGFloat(screen.width * 0.045),
                color: Color(#colorLiteral(red: 0.6666666667, green: 0.3137254902, blue: 0, alpha: 1))),
    SizeCompare(size: CGFloat(screen.width * 0.05),
                color: Color(#colorLiteral(red: 0, green: 0.2196078431, blue: 1, alpha: 1))),
    SizeCompare(size: CGFloat(screen.width * 0.026),
                color: Color(#colorLiteral(red: 0.7843137255, green: 0.3529411765, blue: 0.3141462366, alpha: 1))),
    SizeCompare(size: CGFloat(screen.width * 0.55),
                color: Color(#colorLiteral(red: 1, green: 0.9647058824, blue: 0.6431372549, alpha: 1))),
    SizeCompare(size: CGFloat(screen.width * 0.45),
                color: Color(#colorLiteral(red: 0.9607843137, green: 0.8431372549, blue: 0.2196078431, alpha: 1))),
    SizeCompare(size: CGFloat(screen.width * 0.2),
                color: Color(#colorLiteral(red: 0.4784313725, green: 0.7882352941, blue: 0.7137254902, alpha: 1))),
    SizeCompare(size: CGFloat(screen.width * 0.19),
                color: Color(#colorLiteral(red: 0.4274509804, green: 0.2274509804, blue: 1, alpha: 1)))
]
