//
//  SolarSystemModel.swift
//  SolarisProject
//
//  Created by Felipe Dias on 02/12/20.
//

import SwiftUI

struct Solar: Identifiable {
    var id = UUID()
    var name: String
    var subname: String
    var image: Image
    var color: Color
    var indepth: String
    var day: String
    var year: String
    var radius: String
    var type: String
    var moons: String
    var temperature: String
    var index: Int
    var photo1: Image
    var photo2: Image
    var photo3: Image
    var photo4: Image
    var link1: String
    var link2: String
    var imgTitle1: String
    var imgTitle2: String
    var imgTitle3: String
    var imgTitle4: String
    var source1: String
    var source2: String
    var source3: String
    var source4: String
}

let solarData = [
    Solar(name: "Sun",
          subname: "Our Star",
          image: Image(uiImage: #imageLiteral(resourceName: "sun")),
          color: Color(#colorLiteral(red: 0.8980392157, green: 0.3490196078, blue: 0.1921568662, alpha: 1)),
          indepth: "The Sun is a yellow dwarf star, a hot ball of glowing gases at the heart of our solar system. Its gravity holds everything from the biggest planets to tiny debris in its orbit.",
          day: "N/A",
          year: "N/A",
          radius: "432,686 miles  |  696,340 km",
          type: "Yellow Dwarf",
          moons: "0",
          temperature: "9941ºF  |  5505°C  |  5778 K",
          index: 0,
          photo1: Image(uiImage: #imageLiteral(resourceName: "solsticeflare")),
          photo2: Image(uiImage: #imageLiteral(resourceName: "cover-1920")),
          photo3: Image(uiImage: #imageLiteral(resourceName: "solarfury")),
          photo4: Image(uiImage: #imageLiteral(resourceName: "prominence_sdo_2010090_lrg")),
          link1: "https://solarsystem.nasa.gov/solar-system/sun/in-depth/",
          link2: "https://solarsystem.nasa.gov/solar-system/sun/galleries/?page=0&per_page=25&order=created_at+desc&search=&href_query_params=category%3Dsolar-system_sun&button_class=big_more_button&tags=sun&condition_1=1%3Ais_in_resource_list&category=51",
          imgTitle1: "Sun Emits a Solstice Flare and CME",
          imgTitle2: "Raindrops Falling on the Sun",
          imgTitle3: "Solar Fury",
          imgTitle4: "Prominence from the Solar Dynamics Observatory",
          source1: "NASA/SDO",
          source2: "NASA/GSFC/SDO",
          source3: "NASA's Goddard Space Flight Center",
          source4: "Goddard Space Flight Center Scientific Visualization Studio and the Solar Dynamics Observatory."
          ),
    Solar(name: "Mercury",
          subname: "The Swiftest \nPlanet",
          image: Image(uiImage: #imageLiteral(resourceName: "mercury")),
          color: Color(#colorLiteral(red: 0.3725490196, green: 0.2745098039, blue: 0.4117647059, alpha: 1)),
          indepth: "Mercury is the smallest planet in our solar system and closest to the Sun—is only slightly larger than Earth's Moon. Mercury is the fastest planet, zipping around the Sun every 88 Earth days.",
          day: "176 Earth days",
          year: "88 Earth days",
          radius: "1,516 miles  |  2,440 km",
          type: "Terrestrial",
          moons: "0",
          temperature: "806ºF  |  430°C  |  703 K",
          index: 1,
          photo1: Image(uiImage: #imageLiteral(resourceName: "PIA13508")),
          photo2: Image(uiImage: #imageLiteral(resourceName: "PIA19216")),
          photo3: Image(uiImage: #imageLiteral(resourceName: "PIA16820")),
          photo4: Image(uiImage: #imageLiteral(resourceName: "True_Mercury")),
          link1: "https://solarsystem.nasa.gov/planets/mercury/in-depth/",
          link2: "https://solarsystem.nasa.gov/planets/mercury/galleries/?page=0&per_page=25&order=created_at+desc&search=&href_query_params=category%3Dplanets_mercury&button_class=big_more_button&tags=mercury&condition_1=1%3Ais_in_resource_list&category=51",
          imgTitle1: "Colors of the Innermost Planet: View 1",
          imgTitle2: "Mercury's Caloris Basin",
          imgTitle3: "The Beauty of Calibration",
          imgTitle4: "The Impressive Rays of Hokusai",
          source1: "NASA/Johns Hopkins University Applied Physics Laboratory/Carnegie Institution of Washington",
          source2: "NASA/Johns Hopkins University Applied Physics Laboratory/Carnegie Institution of Washington",
          source3: "NASA",
          source4: "NASA/Johns Hopkins University Applied Physics Laboratory/Carnegie Institution of Washington"
          ),
    Solar(name: "Venus",
          subname: "Planetary \nHot Spot",
          image: Image(uiImage: #imageLiteral(resourceName: "venus")),
          color: Color(#colorLiteral(red: 0.6666666667, green: 0.3137254902, blue: 0, alpha: 1)),
          indepth: "Venus spins slowly in the opposite direction from most planets. A thick atmosphere traps heat in a runaway greenhouse effect, making it the hottest planet in our solar system.",
          day: "243 Earth days",
          year: "225 Earth days",
          radius: "3,760 miles  |  6,052 km",
          type: "Terrestrial",
          moons: "0",
          temperature: "880ºF  |  471°C  |  744 K",
          index: 2,
          photo1: Image(uiImage: #imageLiteral(resourceName: "2524_PIA23791")),
          photo2: Image(uiImage: #imageLiteral(resourceName: "PIA00107")),
          photo3: Image(uiImage: #imageLiteral(resourceName: "f_craterFarm")),
          photo4: Image(uiImage: #imageLiteral(resourceName: "Venus")),
          link1: "https://solarsystem.nasa.gov/planets/venus/in-depth/",
          link2: "https://solarsystem.nasa.gov/planets/venus/galleries/?page=0&per_page=25&order=created_at+desc&search=&href_query_params=category%3Dplanets_venus&button_class=big_more_button&tags=venus&condition_1=1%3Ais_in_resource_list&category=51",
          imgTitle1: "Newly-Processed Views of Venus from Mariner 10",
          imgTitle2: "Venus - 3-D Perspective View of Sapas Mons",
          imgTitle3: "The Crater Farm",
          imgTitle4: "Computer Simulated Global View of Venus",
          source1: "NASA/JPL-Caltech",
          source2: "NASA/JPL",
          source3: "NASA/JPL",
          source4: "NASA/Jet Propulsion Laboratory-Caltech"
          ),
    Solar(name: "Earth",
          subname: "Our Home \nPlanet",
          image: Image(uiImage: #imageLiteral(resourceName: "earth")),
          color: Color(#colorLiteral(red: 0, green: 0.03921568627, blue: 0.5098039216, alpha: 1)),
          indepth: "Earth is our home planet and it’s the only place we know of so far that’s inhabited by living things. It's also the only planet in our solar system with liquid water on the surface.",
          day: "23.9 hours",
          year: "365.25 days",
          radius: "3,959 miles  |  6,371 km",
          type: "Terrestrial",
          moons: "1",
          temperature: "60ºF  |  16°C  |  289 K",
          index: 3,
          photo1: Image(uiImage: #imageLiteral(resourceName: "58_GPN-2000-1090")),
          photo2: Image(uiImage: #imageLiteral(resourceName: "iss059e019043_orig")),
          photo3: Image(uiImage: #imageLiteral(resourceName: "as08-14-2383")),
          photo4: Image(uiImage: #imageLiteral(resourceName: "earth_dscovr_apr19")),
          link1: "https://solarsystem.nasa.gov/planets/earth/in-depth/",
          link2: "https://solarsystem.nasa.gov/planets/earth/galleries/?page=0&per_page=25&order=created_at+desc&search=&href_query_params=category%3Dplanets_earth&button_class=big_more_button&tags=earth&condition_1=1%3Ais_in_resource_list&category=51",
          imgTitle1: "Blue Marble 2002",
          imgTitle2: "Manicouagan Crater",
          imgTitle3: "Apollo 8's Iconic Earthrise",
          imgTitle4: "As the World Turns",
          source1: "NASA's Earth Observatory",
          source2: "International Space Station",
          source3: "NASA/Bill Anders",
          source4: "NOAA/NASA EPIC Team"
          ),
    Solar(name: "Moon",
          subname: "Our Moon",
          image: Image(uiImage: #imageLiteral(resourceName: "earth_moon")),
          color: Color(#colorLiteral(red: 0.2549019754, green: 0.2745098174, blue: 0.3019607961, alpha: 1)),
          indepth: "Earth's Moon is the only place beyond Earth where humans have set foot, so far. The Moon makes our planet more livable by moderating how much it wobbles on its axis.",
          day: "27.3 days",
          year: "27.3 days",
          radius: "1,079.6 miles  |  1,737.5 km",
          type: "Terrestrial",
          moons: "0",
          temperature: "260ºF  |  127°C  |  400 K",
          index: 4,
          photo1: Image(uiImage: #imageLiteral(resourceName: "lro_nearside")),
          photo2: Image(uiImage: #imageLiteral(resourceName: "as11-40-5873_orig")),
          photo3: Image(uiImage: #imageLiteral(resourceName: "20191845091_2fe7e276bf_o")),
          photo4: Image(uiImage: #imageLiteral(resourceName: "14696484257_8b141cfe74_o")),
          link1: "https://solarsystem.nasa.gov/moons/earths-moon/in-depth/",
          link2: "https://solarsystem.nasa.gov/moons/earths-moon/galleries/?page=0&per_page=25&order=created_at+desc&search=&href_query_params=category%3Dmoons_earths-moon&button_class=big_more_button&tags=earth%27s+moon&condition_1=1%3Ais_in_resource_list&category=51",
          imgTitle1: "Lunar Near Side",
          imgTitle2: "Aldrin on the Moon",
          imgTitle3: "Blue Moon and Jet Over Virginia",
          imgTitle4: "Supermoon (2014)",
          source1: "NASA/Goddard Space Flight Center/Arizona State University",
          source2: "NASA",
          source3: "NASA/Joel Kowsky",
          source4: "NASA/Bill Ingalls"
          ),
    Solar(name: "Mars",
          subname: "The Red \nPlanet",
          image: Image(uiImage: #imageLiteral(resourceName: "mars")),
          color: Color(#colorLiteral(red: 0.7843137255, green: 0.3529411765, blue: 0.3141462366, alpha: 1)),
          indepth: "Mars is a dusty, cold, desert world with a very thin atmosphere. There is strong evidence Mars was—billions of years ago—wetter and warmer, with a thicker atmosphere.",
          day: "24.6 hours",
          year: "687 Earth days",
          radius: "2,106 miles | 3,390 km",
          type: "Terrestrial",
          moons: "2",
          temperature: "-20ºF  |  -28°C  |  245 K",
          index: 5,
          photo1: Image(uiImage: #imageLiteral(resourceName: "mars-globe-valles-marineris-enhanced")),
          photo2: Image(uiImage: #imageLiteral(resourceName: "mars-curiosity-rover-gale-crater-beauty-shot-pia19839")),
          photo3: Image(uiImage: #imageLiteral(resourceName: "Sol187B_P2546_L257false-B187R1")),
          photo4: Image(uiImage: #imageLiteral(resourceName: "mars-msl-cropped-pia21716")),
          link1: "https://solarsystem.nasa.gov/planets/mars/in-depth/",
          link2: "https://solarsystem.nasa.gov/planets/mars/galleries/?page=0&per_page=25&order=created_at+desc&search=&href_query_params=category%3Dplanets_mars&button_class=big_more_button&tags=mars&condition_1=1%3Ais_in_resource_list&category=51",
          imgTitle1: "Valles Marineris: The Grand Canyon of Mars",
          imgTitle2: "Dust Haze Hiding the Martian Surface in 2001",
          imgTitle3: "Sunset on Mars (Viking 1)",
          imgTitle4: "Hubble's Close-up View of Mars Dust Storm",
          source1: "NASA/JPL-Caltech ",
          source2: "NASA/JPL-Caltech/MSSS",
          source3: "NASA/JPL",
          source4: "NASA, ESA, and STScI"
          ),
    Solar(name: "Jupiter",
          subname: "Most Massive \nPlanet",
          image: Image(uiImage: #imageLiteral(resourceName: "jupiter")),
          color: Color(#colorLiteral(red: 0.2745098039, green: 0.09803921569, blue: 0.1176470588, alpha: 1)),
          indepth: "Jupiter is more than twice as massive than the other planets of our solar system combined. The giant planet's Great Red spot is a centuries-old storm bigger than Earth.",
          day: "9.93 hours",
          year: "11.86 Earth Years",
          radius: "44,423 miles  |  71,492 km",
          type: "Gas giant",
          moons: "79",
          temperature: "-162ºF  |  -108°C  |  165 K",
          index: 6,
          photo1: Image(uiImage: #imageLiteral(resourceName: "11649_PIA02862")),
          photo2: Image(uiImage: #imageLiteral(resourceName: "192016main_100907_11")),
          photo3: Image(uiImage: #imageLiteral(resourceName: "17385_PIA02879")),
          photo4: Image(uiImage: #imageLiteral(resourceName: "11640_PIA02837")),
          link1: "https://solarsystem.nasa.gov/planets/jupiter/in-depth/",
          link2: "https://solarsystem.nasa.gov/planets/jupiter/galleries/?page=0&per_page=25&order=created_at+desc&search=&href_query_params=category%3Dplanets_jupiter&button_class=big_more_button&tags=jupiter&condition_1=1%3Ais_in_resource_list&category=51",
          imgTitle1: "High Resolution Globe of Jupiter",
          imgTitle2: "Jupiter and Io",
          imgTitle3: "A New Year for Jupiter and Io",
          imgTitle4: "Hubble's New Portrait of Jupiter",
          source1: "NASA/JPL/University of Arizona",
          source2: "NASA/JHUAPL.",
          source3: "NASA/JPL/University of Arizona",
          source4: "NASA, ESA, A. Simon (Goddard Space Flight Center), and M.H. Wong (University of California, Berkeley)"
          ),
    Solar(name: "Saturn",
          subname: "Jewel of Our \nSolar System",
          image: Image(uiImage: #imageLiteral(resourceName: "saturn")),
          color: Color(#colorLiteral(red: 0.5058823824, green: 0.3372549117, blue: 0.06666667014, alpha: 1)),
          indepth: "Adorned with a dazzling, complex system of icy rings, Saturn is unique in our solar system. The other giant planets have rings, but none are as spectacular as Saturn's.",
          day: "10.7 hours",
          year: "29 Earth years",
          radius: "36,183.7 miles  |  58,232 km",
          type: "Gas giant",
          moons: "82",
          temperature: "-218ºF  |  -138°C  |  135 K",
          index: 7,
          photo1: Image(uiImage: #imageLiteral(resourceName: "PIA01364")),
          photo2: Image(uiImage: #imageLiteral(resourceName: "stsci-h-p1943a-f-2076x1484")),
          photo3: Image(uiImage: #imageLiteral(resourceName: "PIA14943-full")),
          photo4: Image(uiImage: #imageLiteral(resourceName: "739460main_ac79-9107.3")),
          link1: "https://solarsystem.nasa.gov/planets/saturn/in-depth/",
          link2: "https://solarsystem.nasa.gov/planets/saturn/galleries/?page=0&per_page=25&order=created_at+desc&search=&href_query_params=category%3Dplanets_saturn&button_class=big_more_button&tags=saturn&condition_1=1%3Ais_in_resource_list&category=51",
          imgTitle1: "Saturn Taken from Voyager 2",
          imgTitle2: "Saturn's Rings Shine in Hubble Portrait",
          imgTitle3: "Translucent Arcs",
          imgTitle4: "Pioneer 11 at Saturn",
          source1: "NASA/JPL",
          source2: "NASA, ESA, A. Simon (GSFC), M.H. Wong (University of California, Berkeley) and the OPAL Team",
          source3: "NASA/JPL-Caltech/Space Science Institute",
          source4: "NASA Ames"
          ),
    Solar(name: "Uranus",
          subname: "The Sideways \nPlanet",
          image: Image(uiImage: #imageLiteral(resourceName: "uranus")),
          color: Color(#colorLiteral(red: 0, green: 0.1568627451, blue: 0.2156862745, alpha: 1)),
          indepth: "Uranus is the seventh planet from the Sun. It rotates at a nearly 90-degree angle from the plane of its orbit. This unique tilt makes Uranus appear to spin on its side.",
          day: "17 hours 14 minutes",
          year: "84 Earth years",
          radius: "15,759.2 miles  |  25,362 km",
          type: "Ice giant",
          moons: "27",
          temperature: "-320ºF  |  -195°C  |  78 K",
          index: 8,
          photo1: Image(uiImage: #imageLiteral(resourceName: "PIA18182")),
          photo2: Image(uiImage: #imageLiteral(resourceName: "PIA01280")),
          photo3: Image(uiImage: #imageLiteral(resourceName: "PIA00143")),
          photo4: Image(uiImage: #imageLiteral(resourceName: "PIA17306")),
          link1: "https://solarsystem.nasa.gov/planets/uranus/in-depth/",
          link2: "https://solarsystem.nasa.gov/planets/uranus/galleries/?page=0&per_page=25&order=created_at+desc&search=&href_query_params=category%3Dplanets_uranus&button_class=big_more_button&tags=uranus&condition_1=1%3Ais_in_resource_list&category=51",
          imgTitle1: "Uranus as seen by NASA's Voyager 2",
          imgTitle2: "Hubble Captures Detailed Image of Uranus' Atmosphere",
          imgTitle3: "Uranus - Final Image",
          imgTitle4: "Keck Telescope Views of Uranus",
          source1: "NASA/JPL",
          source2: "NASA/JPL/STScI",
          source3: "NASA/JPL",
          source4: "Lawrence Sromovsky, University of Wisconsin-Madison/W.W. Keck Observatory"
          ),
    Solar(name: "Neptune",
          subname: "The Blue \nPlanet",
          image: Image(uiImage: #imageLiteral(resourceName: "neptune")),
          color: Color(#colorLiteral(red: 0, green: 0.1176470588, blue: 0.3137254902, alpha: 1)),
          indepth: "Neptune is the eighth and most distant major planet orbiting our Sun. It is dark, cold and whipped by supersonic winds. It was the first planet located through mathematical calculations, rather than by telescope.",
          day: "16 hours",
          year: "165 Earth years",
          radius: "15,299.4 miles  |  24,622 km",
          type: "Ice giant",
          moons: "14",
          temperature: "-331ºF  |  -201°C  |  72 K",
          index: 9,
          photo1: Image(uiImage: #imageLiteral(resourceName: "936_eso1824a")),
          photo2: Image(uiImage: #imageLiteral(resourceName: "PIA01492")),
          photo3: Image(uiImage: #imageLiteral(resourceName: "PIA00058")),
          photo4: Image(uiImage: #imageLiteral(resourceName: "31101484000_02c1a70913_o")),
          link1: "https://solarsystem.nasa.gov/planets/neptune/in-depth/",
          link2: "https://solarsystem.nasa.gov/planets/neptune/galleries/?page=0&per_page=25&order=created_at+desc&search=&href_query_params=category%3Dplanets_neptune&button_class=big_more_button&tags=neptune&condition_1=1%3Ais_in_resource_list&category=51",
          imgTitle1: "Neptune Full Disk View",
          imgTitle2: "Neptune from the Very Large Telescope (VLT)",
          imgTitle3: "Neptune Clouds Showing Vertical Relief",
          imgTitle4: "Neptune - August 31, 1989",
          source1: "NASA/JPL",
          source2: "ESO/P. Weilbacher (AIP)",
          source3: "NASA/JPL",
          source4: "NASA/JPL-Caltech/Kevin M. Gill"
          )
]

struct Buttons: Identifiable {
    var id = UUID()
    var title: String
    var temp: Int
}

let buttonSection = [
    Buttons(title: "Overview", temp: 0),
    Buttons(title: "In Depth", temp: 1),
    Buttons(title: "Photos", temp: 2)
]
